### ISSUE TITLE
permissive license? 

### ISSUE THREAD

**Issue by micahstubbs** [wmurphyrd/adit#36]
this project is really nice.  curious, would you consider using a more permissive license,  like the MIT or BSD license? 

`adit` would likely see more community engagement and pull requests if it were released under a permissive license ☺ 

https://ttmm.io/tech/why-the-mit-license/

https://en.m.wikipedia.org/wiki/MIT_License

**Comment by wmurphyrd** [comment]
Thanks. Some of the plotting code (and all of my data visualization programming knowledge) is derived from a [GPL licensed project](https://github.com/tidyverse/ggplot2), and I support the [pay-it-forward process that the GPL creates](https://www.gnu.org/copyleft/copyleft.html). 

I do plan on packaging up some of the components in Adit, and I'll releasing those under MIT to help as much as possible with getting WebVR kick-started.

**Comment by micahstubbs** [comment]
👍  to publishing A-Frame components

A-Frame has this nice new registry for discovering components:
https://aframe.io/aframe-registry/

and documents how to do it pretty well:
https://aframe.io/docs/0.4.0/introduction/
